// Date & Time Practice

// var now = new Date ();
// console.log(now)

// var now = new Date ();
// var currentHour = now.getHours();
// console.log(currentHour)

// var now = new Date ();
// var today = now.getDate();
// var month = now.getMonth() ;
// var year = now.getFullYear();

// console.log(today + " / " + month  + " / " + year)

// var myBirthday = new Date("September 27, 2002");
// console.log(myBirthday);

// var now = new Date ();
// var time = now.getHours();

// switch(true){
//     case (time < 12):
//     console.log("Good Morning");
//     break;

//     case (time == 12 ):
//     console.log("Good Afetrnoon")
//     break;

//     case (time > 18 ):
//         console.log("Good Evening");
//         break;
// }

// // Age checker
// var user = +prompt("Enter Your Birthyear");
// var currentYear = new Date ().getFullYear();
// var age = currentYear - user;

//  console.log("You're " + age + " Years Old")


// How many days left in next birthday
// var now = new Date();
// var nextBirthday = new Date("27 Sept , 2026");
// var diff = nextBirthday - now;
// var days = Math.floor(diff / (1000 * 60 * 60 * 24))

// console.log(days)

// current time mins sec
// var now = new Date();
// var hour = now.getHours();
// var mins = now.getMinutes();
// var sec = now.getSeconds();

// console.log(hour + " : " + mins + " : "  +sec)


// var today = new Date();
// today.setDate(today.getDate() + 100)

// console.log(today)

// var now = new Date();
// var hour = now.getHours();
// var mins = now.getMinutes();
// var sec = now.getSeconds();


// switch(true){
//     case (hour < 12):
//     console.log("Good Morning");
//     break;

//     case (hour < 18):
//     console.log("Good Afetrnoon")
//     break;

//     default:
//         console.log("Good Evening");
//         break;
// }
// console.log(hour + " : " + mins + " : " + sec)